#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#curl:
#    path: /curl
#    controller: App\Controller\CurlController::index
homepage:
    path: /
    controller: App\Controller\HomepageController::index
site_controller:
    resource: '../src/Controller/'
    type: annotation